//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '$VERSION'.
//
package com.example.operation_based_possible_shapes.selections

import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.notNull
import com.example.operation_based_possible_shapes.type.GraphQLID
import com.example.operation_based_possible_shapes.type.GraphQLString
import com.example.operation_based_possible_shapes.type.PetOwner
import com.example.operation_based_possible_shapes.type.ThingWithID
import kotlin.collections.List

public object TestOperationSelections {
  private val __onHuman: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __onDroid: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "build_name",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "model_name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __onHuman1: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __onDroid1: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "build_name",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "model_name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __owner: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Human",
          possibleTypes = listOf("Human")
        ).selections(__onHuman1)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "Droid",
          possibleTypes = listOf("Droid")
        ).selections(__onDroid1)
        .build()
      )

  private val __onPet: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "owner",
          type = PetOwner.type.notNull()
        ).selections(__owner)
        .build()
      )

  private val __onThingWithName: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __something: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Human",
          possibleTypes = listOf("Human")
        ).selections(__onHuman)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "Droid",
          possibleTypes = listOf("Droid")
        ).selections(__onDroid)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "Pet",
          possibleTypes = listOf("Pet")
        ).selections(__onPet)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "ThingWithName",
          possibleTypes = listOf("Human", "Pet")
        ).selections(__onThingWithName)
        .build()
      )

  private val __something1: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build()
      )

  public val __root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "something",
          type = ThingWithID.type
        ).selections(__something)
        .build(),
        CompiledField.Builder(
          name = "something",
          type = ThingWithID.type
        ).alias("somethingWithOnlyOneShape")
        .selections(__something1)
        .build()
      )
}
