//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.__mytest.selections

import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.notNull
import com.example.__mytest.type.Friend
import com.example.__mytest.type.GraphQLID
import com.example.__mytest.type.GraphQLString
import com.example.__mytest.type.LifeStatus
import com.example.__mytest.type.ThingWithID
import kotlin.collections.List

public object TestOperationSelections {
  private val __onHuman1: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __onHuman2: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __friend: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Human",
          possibleTypes = listOf("Human")
        ).selections(__onHuman1)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "Human2",
          possibleTypes = listOf("Human2")
        ).selections(__onHuman2)
        .build()
      )

  private val __onHuman: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "life_status",
          type = LifeStatus.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "friend",
          type = Friend.type.notNull()
        ).selections(__friend)
        .build()
      )

  private val __onThingWithName: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "name",
          type = GraphQLString.type.notNull()
        ).build()
      )

  private val __something: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Human",
          possibleTypes = listOf("Human")
        ).selections(__onHuman)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "ThingWithName",
          possibleTypes = listOf("Human", "Human2", "Droid")
        ).selections(__onThingWithName)
        .build()
      )

  public val __root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "something",
          type = ThingWithID.type
        ).selections(__something)
        .build()
      )
}
