//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.String

public data class DroidFragment(
  public val model_name: String,
  public val build_name: String,
) : Fragment.Data
