//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.String

public interface IPetOwnerFragment : Fragment.Data {
  public val __typename: String

  /**
   * Synthetic field for inline fragment on Human
   */
  public val onHuman: PetOwnerFragment.OnHuman?

  /**
   * Synthetic field for inline fragment on Droid
   */
  public val onDroid: PetOwnerFragment.OnDroid?
}

public data class HumanPetOwnerFragment(
  public override val __typename: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: PetOwnerFragment.OnHuman,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: PetOwnerFragment.OnDroid?,
) : IPetOwnerFragment

public data class DroidPetOwnerFragment(
  public override val __typename: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: PetOwnerFragment.OnHuman?,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: PetOwnerFragment.OnDroid,
) : IPetOwnerFragment

public data class PetOwnerFragment(
  public override val __typename: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: OnHuman?,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: OnDroid?,
) : IPetOwnerFragment {
  public data class OnHuman(
    public val id: String,
    public val name: String,
  )

  public data class OnDroid(
    public val id: String,
    public val build_name: String,
    public val model_name: String,
  )
}
