//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment.fragment

import com.apollographql.apollo3.api.Fragment
import kotlin.String

public interface IThingWithIDFragment : Fragment.Data {
  public val __typename: String

  public val id: String

  /**
   * Synthetic field for inline fragment on Human
   */
  public val onHuman: ThingWithIDFragment.OnHuman?

  /**
   * Synthetic field for inline fragment on Droid
   */
  public val onDroid: ThingWithIDFragment.OnDroid?

  /**
   * Synthetic field for inline fragment on Pet
   */
  public val onPet: ThingWithIDFragment.OnPet?
}

public data class HumanThingWithIDFragment(
  public override val __typename: String,
  public override val id: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: ThingWithIDFragment.OnHuman,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: ThingWithIDFragment.OnDroid?,
  /**
   * Synthetic field for inline fragment on Pet
   */
  public override val onPet: ThingWithIDFragment.OnPet?,
) : IThingWithIDFragment

public data class DroidThingWithIDFragment(
  public override val __typename: String,
  public override val id: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: ThingWithIDFragment.OnHuman?,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: ThingWithIDFragment.OnDroid,
  /**
   * Synthetic field for inline fragment on Pet
   */
  public override val onPet: ThingWithIDFragment.OnPet?,
) : IThingWithIDFragment

public data class PetThingWithIDFragment(
  public override val __typename: String,
  public override val id: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: ThingWithIDFragment.OnHuman?,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: ThingWithIDFragment.OnDroid?,
  /**
   * Synthetic field for inline fragment on Pet
   */
  public override val onPet: ThingWithIDFragment.OnPet,
) : IThingWithIDFragment

public data class ThingWithIDFragment(
  public override val __typename: String,
  public override val id: String,
  /**
   * Synthetic field for inline fragment on Human
   */
  public override val onHuman: OnHuman?,
  /**
   * Synthetic field for inline fragment on Droid
   */
  public override val onDroid: OnDroid?,
  /**
   * Synthetic field for inline fragment on Pet
   */
  public override val onPet: OnPet?,
) : IThingWithIDFragment {
  public data class OnHuman(
    public val name: String,
  )

  public data class OnDroid(
    public val build_name: String,
    public val model_name: String,
  )

  public data class OnPet(
    public val name: String,
    public val owner: IOwner,
  ) {
    public interface IOwner {
      public val __typename: String

      /**
       * Synthetic field for 'PetOwnerFragment'
       */
      public val petOwnerFragment: PetOwnerFragment
    }

    public data class HumanOwner(
      public override val __typename: String,
      /**
       * Synthetic field for 'PetOwnerFragment'
       */
      public override val petOwnerFragment: PetOwnerFragment,
    ) : IOwner

    public data class DroidOwner(
      public override val __typename: String,
      /**
       * Synthetic field for 'PetOwnerFragment'
       */
      public override val petOwnerFragment: PetOwnerFragment,
    ) : IOwner

    public data class Owner(
      public override val __typename: String,
      /**
       * Synthetic field for 'PetOwnerFragment'
       */
      public override val petOwnerFragment: PetOwnerFragment,
    ) : IOwner
  }
}
