//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment.fragment

import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Fragment
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.example.operation_based_possible_shapes_fragment.fragment.selections.ThingWithIDFragmentSelections
import com.example.operation_based_possible_shapes_fragment.type.ThingWithID
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Unit

public class ThingWithIDFragmentImpl() : Fragment<IThingWithIDFragment> {
  public override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  public override fun hashCode(): Int = this::class.hashCode()

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    // This fragment doesn't have any variable
  }

  public override fun adapter(): Adapter<IThingWithIDFragment> =
      ThingWithIDFragmentImpl_ResponseAdapter.IThingWithIDFragment.obj(true)

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = ThingWithID.type
  )
  .selections(selections = ThingWithIDFragmentSelections.__root)
  .build()
}
