//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment.selections

import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CompiledFragment
import com.apollographql.apollo3.api.CompiledSelection
import com.apollographql.apollo3.api.notNull
import com.example.operation_based_possible_shapes_fragment.fragment.selections.DroidFragmentSelections
import com.example.operation_based_possible_shapes_fragment.fragment.selections.HumanFragmentSelections
import com.example.operation_based_possible_shapes_fragment.fragment.selections.ThingWithIDFragmentSelections
import com.example.operation_based_possible_shapes_fragment.fragment.selections.ThingWithNameFragmentSelections
import com.example.operation_based_possible_shapes_fragment.type.GraphQLID
import com.example.operation_based_possible_shapes_fragment.type.GraphQLString
import com.example.operation_based_possible_shapes_fragment.type.ThingWithID
import kotlin.collections.List

public object TestOperationSelections {
  private val __something: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "ThingWithID",
          possibleTypes = listOf("Human", "Droid", "Pet")
        ).selections(ThingWithIDFragmentSelections.__root)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "ThingWithName",
          possibleTypes = listOf("Human", "Pet")
        ).selections(ThingWithNameFragmentSelections.__root)
        .build()
      )

  private val __onDroid: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Droid",
          possibleTypes = listOf("Droid")
        ).selections(DroidFragmentSelections.__root)
        .build()
      )

  private val __something1: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "__typename",
          type = GraphQLString.type.notNull()
        ).build(),
        CompiledField.Builder(
          name = "id",
          type = GraphQLID.type.notNull()
        ).build(),
        CompiledFragment.Builder(
          typeCondition = "Human",
          possibleTypes = listOf("Human")
        ).selections(HumanFragmentSelections.__root)
        .build(),
        CompiledFragment.Builder(
          typeCondition = "Droid",
          possibleTypes = listOf("Droid")
        ).selections(__onDroid)
        .build()
      )

  public val __root: List<CompiledSelection> = listOf(
        CompiledField.Builder(
          name = "something",
          type = ThingWithID.type
        ).selections(__something)
        .build(),
        CompiledField.Builder(
          name = "something",
          type = ThingWithID.type
        ).alias("something2")
        .selections(__something1)
        .build()
      )
}
