//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment

import com.apollographql.apollo3.annotations.ApolloAdaptableWith
import com.apollographql.apollo3.api.Adapter
import com.apollographql.apollo3.api.CompiledField
import com.apollographql.apollo3.api.CustomScalarAdapters
import com.apollographql.apollo3.api.Query
import com.apollographql.apollo3.api.json.JsonWriter
import com.apollographql.apollo3.api.obj
import com.example.operation_based_possible_shapes_fragment.adapter.TestOperation_ResponseAdapter
import com.example.operation_based_possible_shapes_fragment.fragment.DroidFragment
import com.example.operation_based_possible_shapes_fragment.fragment.HumanFragment
import com.example.operation_based_possible_shapes_fragment.fragment.ThingWithIDFragment
import com.example.operation_based_possible_shapes_fragment.fragment.ThingWithNameFragment
import com.example.operation_based_possible_shapes_fragment.selections.TestOperationSelections
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.Unit

public class TestOperation() : Query<TestOperation.Data> {
  public override fun equals(other: Any?): Boolean = other != null && other::class == this::class

  public override fun hashCode(): Int = this::class.hashCode()

  public override fun id(): String = OPERATION_ID

  public override fun document(): String = OPERATION_DOCUMENT

  public override fun name(): String = OPERATION_NAME

  public override fun serializeVariables(writer: JsonWriter,
      customScalarAdapters: CustomScalarAdapters): Unit {
    // This operation doesn't have any variable
  }

  public override fun adapter(): Adapter<Data> = TestOperation_ResponseAdapter.Data.obj()

  public override fun rootField(): CompiledField = CompiledField.Builder(
    name = "data",
    type = com.example.operation_based_possible_shapes_fragment.type.Query.type
  )
  .selections(selections = TestOperationSelections.__root)
  .build()

  @ApolloAdaptableWith(TestOperation_ResponseAdapter.Data::class)
  public data class Data(
    public val something: ISomething?,
    public val something2: ISomething2?,
  ) : Query.Data {
    public sealed interface ISomething {
      public val __typename: String

      /**
       * Synthetic field for 'ThingWithIDFragment'
       */
      public val thingWithIDFragment: ThingWithIDFragment

      /**
       * Synthetic field for 'ThingWithNameFragment'
       */
      public val thingWithNameFragment: ThingWithNameFragment?
    }

    public data class DroidSomething(
      public override val __typename: String,
      /**
       * Synthetic field for 'ThingWithIDFragment'
       */
      public override val thingWithIDFragment: ThingWithIDFragment,
      /**
       * Synthetic field for 'ThingWithNameFragment'
       */
      public override val thingWithNameFragment: ThingWithNameFragment?,
    ) : ISomething

    public data class HumanThingWithNameSomething(
      public override val __typename: String,
      /**
       * Synthetic field for 'ThingWithIDFragment'
       */
      public override val thingWithIDFragment: ThingWithIDFragment,
      /**
       * Synthetic field for 'ThingWithNameFragment'
       */
      public override val thingWithNameFragment: ThingWithNameFragment,
    ) : ISomething

    public data class PetThingWithNameSomething(
      public override val __typename: String,
      /**
       * Synthetic field for 'ThingWithIDFragment'
       */
      public override val thingWithIDFragment: ThingWithIDFragment,
      /**
       * Synthetic field for 'ThingWithNameFragment'
       */
      public override val thingWithNameFragment: ThingWithNameFragment,
    ) : ISomething

    public data class Something(
      public override val __typename: String,
      /**
       * Synthetic field for 'ThingWithIDFragment'
       */
      public override val thingWithIDFragment: ThingWithIDFragment,
      /**
       * Synthetic field for 'ThingWithNameFragment'
       */
      public override val thingWithNameFragment: ThingWithNameFragment?,
    ) : ISomething

    public sealed interface ISomething2 {
      public val __typename: String

      public val id: String

      /**
       * Synthetic field for inline fragment on Droid
       */
      public val onDroid: Something2.OnDroid?

      /**
       * Synthetic field for 'HumanFragment'
       */
      public val humanFragment: HumanFragment?
    }

    public data class HumanSomething2(
      public override val __typename: String,
      public override val id: String,
      /**
       * Synthetic field for inline fragment on Droid
       */
      public override val onDroid: Something2.OnDroid?,
      /**
       * Synthetic field for 'HumanFragment'
       */
      public override val humanFragment: HumanFragment,
    ) : ISomething2

    public data class DroidSomething2(
      public override val __typename: String,
      public override val id: String,
      /**
       * Synthetic field for inline fragment on Droid
       */
      public override val onDroid: Something2.OnDroid,
      /**
       * Synthetic field for 'HumanFragment'
       */
      public override val humanFragment: HumanFragment?,
    ) : ISomething2

    public data class Something2(
      public override val __typename: String,
      public override val id: String,
      /**
       * Synthetic field for inline fragment on Droid
       */
      public override val onDroid: OnDroid?,
      /**
       * Synthetic field for 'HumanFragment'
       */
      public override val humanFragment: HumanFragment?,
    ) : ISomething2 {
      public data class OnDroid(
        public val __typename: String,
        /**
         * Synthetic field for 'DroidFragment'
         */
        public val droidFragment: DroidFragment,
      )
    }
  }

  public companion object {
    public const val OPERATION_ID: String =
        "9d7aa48d49c312f65d344b42fc4ad137eca8872e89205f9b3aaaedf27eda85dc"

    /**
     * The minimized GraphQL document being sent to the server to save a few bytes.
     * The un-minimized version is:
     *
     * query TestOperation {
     *   something {
     *     __typename
     *     ...ThingWithIDFragment
     *     ...ThingWithNameFragment
     *   }
     *   something2: something {
     *     __typename
     *     id
     *     ...HumanFragment
     *     ... on Droid {
     *       __typename
     *       ...DroidFragment
     *     }
     *   }
     * }
     *
     * fragment PetOwnerFragment on PetOwner {
     *   __typename
     *   ... on Human {
     *     id
     *     name
     *   }
     *   ... on Droid {
     *     id
     *     build_name
     *     model_name
     *   }
     * }
     *
     * fragment ThingWithIDFragment on ThingWithID {
     *   __typename
     *   id
     *   ... on Human {
     *     name
     *   }
     *   ... on Droid {
     *     build_name
     *     model_name
     *   }
     *   ... on Pet {
     *     name
     *     owner {
     *       __typename
     *       ...PetOwnerFragment
     *     }
     *   }
     * }
     *
     * fragment ThingWithNameFragment on ThingWithName {
     *   name
     * }
     *
     * fragment HumanFragment on Human {
     *   name
     * }
     *
     * fragment DroidFragment on Droid {
     *   model_name
     *   build_name
     * }
     */
    public val OPERATION_DOCUMENT: String
      get() =
          "query TestOperation { something { __typename ...ThingWithIDFragment ...ThingWithNameFragment } something2: something { __typename id ...HumanFragment ... on Droid { __typename ...DroidFragment } } }  fragment PetOwnerFragment on PetOwner { __typename ... on Human { id name } ... on Droid { id build_name model_name } }  fragment ThingWithIDFragment on ThingWithID { __typename id ... on Human { name } ... on Droid { build_name model_name } ... on Pet { name owner { __typename ...PetOwnerFragment } } }  fragment ThingWithNameFragment on ThingWithName { name }  fragment HumanFragment on Human { name }  fragment DroidFragment on Droid { model_name build_name }"

    public const val OPERATION_NAME: String = "TestOperation"
  }
}
