//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_interesting_types.type

import com.apollographql.apollo3.api.CustomScalarType

/**
 * The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent
 * values between -(2^31) and 2^31 - 1.
 */
public class GraphQLInt {
  public companion object {
    public val type: CustomScalarType = CustomScalarType("Int", "kotlin.Int")
  }
}
