//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.operation_based_possible_shapes_fragment.type

import com.apollographql.apollo3.api.InterfaceType

public class ThingWithName {
  public companion object {
    public val type: InterfaceType = InterfaceType.Builder(name = "ThingWithName").build()
  }
}
