//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.__mytest.type

import com.apollographql.apollo3.api.UnionType

public class Friend {
  public companion object {
    public val type: UnionType = UnionType("Friend", Human.type, Human2.type)
  }
}
