//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '3.5.1-SNAPSHOT'.
//
package com.example.__mytest.type

import kotlin.String

/**
 * Auto generated enum class for enumerable possible type of ThingWithID
 */
public enum class ThingWithIDPossibleTypes(
  public val rawValue: String,
) {
  Human("Human"),
  Human2("Human2"),
  Droid("Droid"),
  /**
   * Auto generated constant for unknown __typename values
   */
  UNKNOWN__("UNKNOWN__"),
  ;

  public companion object {
    public fun safeValueOf(rawValue: String): ThingWithIDPossibleTypes =
        values().find { it.rawValue == rawValue } ?: UNKNOWN__
  }
}
