//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '$VERSION'.
//
package com.example.operation_based_possible_shapes.type

import com.apollographql.apollo3.api.CustomScalarType

/**
 * The `Boolean` scalar type represents `true` or `false`.
 */
public class GraphQLBoolean {
  public companion object {
    public val type: CustomScalarType = CustomScalarType("Boolean", "kotlin.Boolean")
  }
}
