//
// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL version '$VERSION'.
//
package com.example.operation_based_possible_shapes.type

import com.apollographql.apollo3.api.UnionType

public class PetOwner {
  public companion object {
    public val type: UnionType = UnionType("PetOwner", Human.type, Droid.type)
  }
}
